workflows:
  version: 2
  flow:
    jobs:
      - sourcecodeless
      - scan:
          requires:
            - sourcecodeless

jobs:
  sourcecodeless:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    environment:
      TERM: dumb

    steps:
      - checkout
      - run: sh ./gradlew dependencies > .debricked-gradle-dependencies.txt
      # it is important that the generated dependency tree is persisted and attached to the following scan step
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .debricked-gradle-dependencies.txt

  scan:
    docker:
      # circleci ignores the entrypoint of debricked-scan, so start the scan manually with a step
      - image: debricked/debricked-scan
    
    working_directory: ~/repo
    
    # set debricked username and password in DEBRICKED_USERNAME and DEBRICKED_PASSWORD respectively,
    # to avoid storing them in config
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: |
          USERNAME="${DEBRICKED_USERNAME}"
          PASSWORD="${DEBRICKED_PASSWORD}"
          REPOSITORY="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
          COMMIT="${CIRCLE_SHA1}"
          BRANCH="${CIRCLE_BRANCH}"
          BASE_DIRECTORY=${BASE_DIRECTORY:=""}
          REPOSITORY_URL=${CIRCLE_REPOSITORY_URL}
          INTEGRATION_NAME=circleci
          source /common.sh
