version: 2.1

jobs:
  build:
    docker:
    - image: circleci/openjdk:11-jdk

    working_directory: ~/repo

    steps:
    - checkout
    - run: sh ./gradlew dependencies > .debricked-gradle-dependencies.txt
    - persist_to_workspace:
        root: ~/repo
        paths:
        - .debricked-gradle-dependencies.txt

  scan:
    docker:
    - image: debricked/debricked-scan

    working_directory: ~/repo

    steps:
    - checkout
    - attach_workspace:
        at: ~/repo
    - run: bash /circleci.sh

workflows:
  debricked-scan:
    jobs:
    - build
    - scan:
        requires:
        - build
