# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

workflows:
  version: 2
  flow:
    jobs:
      - sourcecodeless
      - scan:
          requires:
            - sourcecodeless

jobs:
  sourcecodeless:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: sh ./gradlew dependencies > .debricked-gradle-dependencies.txt
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .debricked-gradle-dependencies.txt

  scan:
    docker:
      - image: node:14
    
    working_directory: ~/repo

    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: find .
      - run: find ~/repo
